### ISSUE TITLE
Module lists 'local' provider as dependency but it is never used

### ISSUE THREAD

**Issue by darend** [cloudposse/terraform-aws-s3-log-storage#24]
Can you remove the explicit dependency on the `local` provider. It is unused

See https://github.com/cloudposse/terraform-aws-s3-log-storage/blob/2c2588c9e451b4f6dcf0fd103966c4fd54d48364/versions.tf#L6

**Comment by Gowiem** [comment]
@darend the local provider is no longer listed in the [`versions.tf`](https://github.com/cloudposse/terraform-aws-s3-log-storage/blob/master/versions.tf) file. Please let us know if you see otherwise. Thanks!
