### ISSUE TITLE
Could you please add S3 server access logging option to this module?

### ISSUE THREAD

**Issue by gitmor** [cloudposse/terraform-aws-s3-log-storage#26]
Please add logging option to this module so that users of this module can provide an s3 access logging bucket as input. It would be very useful to have since many security rules expect S3 server access logging to be setup for all S3 buckets. So anyone that has that restriction won't be able to use this module (per my understanding) and would have to manually add the server access logging through console.
So the next time, terraform plan will show this change & terraform apply it will revert the manual change back.

**Comment by jamengual** [comment]
this module is to create such bucket. this is somewhat a chicken and egg problem, which one you create first?
if we do this we will be creating yet another bucket for logging and what will happen to that bucket, it will need a log bucket too, and so on....

CloudTrail can be used to log bucket access too so you could use that to log bucket access to the log bucket if you must
