### ISSUE TITLE
A default policy should be in place to enforce TLS

### ISSUE THREAD

**Issue by lazzurs** [cloudposse/terraform-aws-s3-log-storage#41]
## Describe the Feature

The AWS Foundational Security Best Practices suggests a bucket policy to enforce TLS. This should be a feature of this module.

## Expected Behavior

Either the policy should be applied to all logs buckets or it should be an option to apply this policy.

## Use Case

Looking to ensure our accounts follow AWS Foundational Security Best Practices and we use this module for our logs buckets.

## Describe Ideal Solution

The bucket policy to enforce TLS being applied to all log buckets by default.

## Alternatives Considered

This policy can just be applied by users by passing in the policy via the variable but as part of AWS best practices this could be a feature of this module.

## Additional Context

I am happy to write the feature in but would like some guidance on if you want this as a feature that can be toggled or just a default.

Below is the link to the AWS guidance on this.

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-5

**Comment by Gowiem** [comment]
@lazzurs This is now supported via `allow_ssl_requests_only`. It defaults to false, but can be enabled easily enough. 

Thanks for opening. I'm going to close out, but please reopen if you have any questions or this is not what you had in mind.
