### ISSUE TITLE
Terraform 1.0 not supported

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [cloudposse/terraform-aws-s3-log-storage#58]
## Describe the Bug
Terraform 1.0 fails to init.

## Expected Behavior
Terraform 1.0 successfully inits.

## Steps to Reproduce
Try to init with Terraform 1.0:
```
Error: Unsupported Terraform Core version
 
   on .terraform/modules/s3_log_storage.this/versions.tf line 2, in terraform:
    2:   required_version = ">= 0.12.0, < 0.14.0"
 
 Module module.s3_log_storage.module.this (from
 git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2)
 does not support Terraform version 1.0.0. To proceed, either choose another
 supported Terraform version or update this version constraint. Version
 constraints are normally set for good reason, so updating the constraint
 may lead to other errors or unexpected behavior.
```

## Environment (please complete the following information):

Terraform 1.0

**Comment by Gowiem** [comment]
@mateuszkwiatkowski v0.24 of this module utilizes `>= 0.13.0` for its terraform version requirement. Can you share your configuration and let us know what version of the module you're utilizing?

**Comment by Gowiem** [comment]
I'm going to close out. Please reopen if I'm incorrect on the above or if you have any questions -- Thanks!
