### ISSUE TITLE
Can you update the `cloudposse/terraform-aws-s3-bucket` version to at least version 2.0.1?

### ISSUE THREAD

**Issue by amontalban** [cloudposse/terraform-aws-s3-log-storage#74]
I'm getting the message described in cloudposse/terraform-aws-s3-bucket#148 and since this is a greenfield deployment I would like to have it defined properly to avoid having drifts in the config.

Thanks!

**Comment by mwos-sl** [comment]
Got the same in downstream dependancy: https://github.com/cloudposse/terraform-aws-lb-s3-bucket/issues/55

**Comment by mwos-sl** [comment]
Can be closed, done with: https://github.com/cloudposse/terraform-aws-s3-log-storage/pull/76
